version: '3.9'

networks:
  net:
    driver: bridge

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile_UI
    command: streamlit run ./app/app.py --server.port=80 --server.address=0.0.0.0
    environment:
      PORT: 80
      WEB_CONCURRENCY: 1
    ports:
      - 80:80
    networks:
      - net

  backend:
    build:
      context: .
      dockerfile: Dockerfile_FastAPI
    command: uvicorn app.main:app --host 0.0.0.0 --port 8008
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    environment:
      WEB_CONCURRENCY: 1
    ports:
      - 8008:8008
    # network_mode: "host" 
    networks:
      - net

  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/chroma
      - index_data:/index_data
    command: uvicorn chromadb.app:app --reload --workers 1 --host 0.0.0.0 --port 8000 --log-config log_config.yml
    environment:
      - CHROMA_DB_IMPL=clickhouse
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
    ports:
      - 8000:8000
    depends_on:
      - clickhouse
    networks:
      - net

  clickhouse:
    image: clickhouse/clickhouse-server:22.9-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - CLICKHOUSE_TCP_PORT=9000
      - CLICKHOUSE_HTTP_PORT=8123
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - clickhouse_data:/bitnami/clickhouse
      - backups:/backups
      - ./config/backup_disk.xml:/etc/clickhouse-server/config.d/backup_disk.xml
      - ./config/chroma_users.xml:/etc/clickhouse-server/users.d/chroma.xml
    networks:
      - net

volumes:
  clickhouse_data:
    driver: local
  index_data:
    driver: local
  backups:
    driver: local
